name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Download Dependencies
        run: go mod download

      - name: Check Formatting
        run: |
          test -z "$(gofmt -l .)"

      - name: Go Vet
        run: go vet ./...

      - name: Build Application
        run: go build -v ./...

      - name: Build Docker Image
        run: docker build -t dinsos-backend:test .